package jdk.jfr.consumer;

import java.util.List;

import jdk.jfr.ValueDescriptor;

/**
 * A method, as it was recorded.
 *
 * <p>{@link #getDescriptor} returns the descriptor of the JVM, such as
 * {@code "(Ljava/lang/String;)I"}. It is what tells two overloads of the same name apart, and
 * without it a stack of calls cannot be resolved against the code -- which is what a profiler needs
 * to do.
 *
 * <p>{@link #isHidden} marks the methods the VM generates and which are in no source: the bodies of
 * the lambdas, the adapters of the method handles. A tool hides them by default because they dirty
 * the stack without saying anything.
 *
 * @since 9
 */
public final class RecordedMethod extends RecordedObject {

    RecordedMethod(List<ValueDescriptor> descriptors, Object[] values) {
        super(descriptors, values);
    }

    /**
     * The class that declares the method.
     *
     * @return the class
     */
    public RecordedClass getType() {
        return getClass("type");
    }

    /**
     * The name of the method.
     *
     * @return the name
     */
    public String getName() {
        return getString("name");
    }

    /**
     * The descriptor of the JVM.
     *
     * @return the descriptor
     */
    public String getDescriptor() {
        return getString("descriptor");
    }

    /**
     * The modifiers of the method.
     *
     * @return the modifiers
     */
    public int getModifiers() {
        return getInt("modifiers");
    }

    /**
     * Whether it is a method generated by the VM.
     *
     * @return whether it is hidden
     */
    public boolean isHidden() {
        return getBoolean("hidden");
    }
}
