package com.sun.management;

/**
 * The threads, with the question the standard interface does not ask: how much memory each one
 * asked for.
 *
 * <h2>Why the allocation per thread is such a useful datum</h2>
 *
 * <p>Because the garbage is not generated by "the program": it is generated by some thread,
 * and almost always by a few. The totals of {@link java.lang.management.MemoryMXBean} say how
 * much was collected and do not say who produced it, which is the only thing that serves in
 * order to fix it.
 *
 * <p>The counter is <strong>cumulative and monotonic</strong>: it counts everything the thread
 * asked for since it started, without subtracting what was collected. That is why the way of
 * using it is to take two readings and subtract them -- the absolute value of a single one says
 * nothing.
 *
 * <h2>Why it has to be enabled</h2>
 *
 * <p>Because measuring costs. {@link #isThreadAllocatedMemorySupported} says whether the VM
 * can, {@link #isThreadAllocatedMemoryEnabled} whether it is measuring now, and
 * {@link #setThreadAllocatedMemoryEnabled} turns it on. A thread that ran with the measurement
 * turned off does not have the datum, not even retroactively.
 *
 * <h2>The versions that take an array</h2>
 *
 * <p>{@link #getThreadCpuTime(long[])} and its companions exist because of the cost of crossing
 * into the VM. A monitor that shows two hundred threads would make two hundred calls, each one
 * with its suspension; with the array it makes one. The result is in the same order as the
 * input, and a position is worth {@code -1} if that thread no longer exists.
 *
 * @since 1.5
 */
public interface ThreadMXBean extends java.lang.management.ThreadMXBean {

    /**
     * The CPU time of several threads, in nanoseconds.
     *
     * @param ids the identifiers
     * @return the times, in the same order; {@code -1} where the thread does not exist or was not
     *     measured
     */
    long[] getThreadCpuTime(long[] ids);

    /**
     * The CPU time in user mode of several threads, in nanoseconds.
     *
     * @param ids the identifiers
     * @return the times, in the same order; {@code -1} where the thread does not exist or was not
     *     measured
     */
    long[] getThreadUserTime(long[] ids);

    /**
     * The total memory asked for by all the threads, alive and finished, in bytes.
     *
     * <p>It is the only counter that includes the threads that have already died, and that is why
     * it is the one that serves for the process's total: adding the live ones up leaves out
     * everything a short-lived thread allocated, which tends to be most of it.
     *
     * @return the bytes, or {@code -1} if there is no datum
     * @throws UnsupportedOperationException if the VM cannot measure the allocation per thread
     */
    default long getTotalThreadAllocatedBytes() {
        if (!isThreadAllocatedMemorySupported()) {
            throw new UnsupportedOperationException(
                    "Thread allocated memory measurement is not supported.");
        }
        return -1L;
    }

    /**
     * The memory asked for by the calling thread, in bytes.
     *
     * @return the bytes, or {@code -1} if the measurement is turned off
     * @throws UnsupportedOperationException if the VM cannot measure the allocation per thread
     */
    default long getCurrentThreadAllocatedBytes() {
        return getThreadAllocatedBytes(Thread.currentThread().threadId());
    }

    /**
     * The memory asked for by a thread, in bytes.
     *
     * @param id the thread's identifier
     * @return the bytes, or {@code -1} if the thread does not exist or the measurement is turned
     *     off
     * @throws IllegalArgumentException if the identifier is not positive
     * @throws UnsupportedOperationException if the VM cannot measure the allocation per thread
     */
    long getThreadAllocatedBytes(long id);

    /**
     * The memory asked for by several threads, in bytes.
     *
     * @param ids the identifiers
     * @return the bytes, in the same order; {@code -1} where the thread does not exist or was not
     *     measured
     * @throws IllegalArgumentException if some identifier is not positive
     * @throws UnsupportedOperationException if the VM cannot measure the allocation per thread
     */
    long[] getThreadAllocatedBytes(long[] ids);

    /**
     * Whether this VM can measure the allocation per thread.
     *
     * @return whether it can
     */
    boolean isThreadAllocatedMemorySupported();

    /**
     * Whether it is measuring it now.
     *
     * @return whether it is turned on
     * @throws UnsupportedOperationException if the VM cannot measure it
     */
    boolean isThreadAllocatedMemoryEnabled();

    /**
     * It turns the measurement on or off.
     *
     * @param enable whether to turn it on
     * @throws UnsupportedOperationException if the VM cannot measure it
     */
    void setThreadAllocatedMemoryEnabled(boolean enable);
}
