package javax.management.remote.rmi;

import java.io.IOException;
import java.lang.reflect.Method;
import java.rmi.RemoteException;
import java.rmi.UnexpectedException;
import java.rmi.server.RemoteRef;
import java.rmi.server.RemoteStub;

/**
 * {@link RMIServerImpl}'s stub: what the client holds in its hand.
 *
 * <h2>What a stub is</h2>
 *
 * <p>An object that implements the same interface as the one over there and does nothing by
 * itself: each method packs the arguments and passes them to the {@link RemoteRef}, which is the
 * one that knows how to reach the other machine. The {@link Hash number} that accompanies each
 * call is what tells the other side which of the methods was invoked.
 *
 * <p>That the code is so mechanical is no coincidence: in the JDK this class is generated by
 * {@code rmic}. Here it is written out, with the only difference that the numbers are computed
 * when the class is loaded instead of being put in as literals.
 *
 * <h2>State in this VM</h2>
 *
 * <p>The class works: it builds, computes the numbers correctly and calls the reference. What
 * there is not is anywhere to get a live {@link RemoteRef} from, because that is the transport.
 * A stub built with a reference that leads nowhere fails in the reference, which is where it
 * should.
 *
 * @since 1.5
 */
public final class RMIServerImpl_Stub extends RemoteStub implements RMIServer {

    private static final long serialVersionUID = 2L;

    private static Method $method_getVersion_0;
    private static Method $method_newClient_1;

    private static long $hash_getVersion_0;
    private static long $hash_newClient_1;

    static {
        try {
            $method_getVersion_0 = RMIServer.class.getMethod("getVersion");
            $method_newClient_1 = RMIServer.class.getMethod("newClient", Object.class);
        } catch (NoSuchMethodException e) {
            throw new NoSuchMethodError("stub class initialization failed");
        }
        $hash_getVersion_0 = Hash.de($method_getVersion_0);
        $hash_newClient_1 = Hash.de($method_newClient_1);
    }

    /**
     * A stub over that reference.
     *
     * @param ref the reference that knows how to reach the remote object
     */
    public RMIServerImpl_Stub(RemoteRef ref) {
        super(ref);
    }

    /**
     * The protocol's and the provider's version, asked of the other side.
     *
     * @return the version
     * @throws RemoteException if the server could not be talked to
     */
    public String getVersion() throws RemoteException {
        try {
            final Object r = ref.invoke(this, $method_getVersion_0, null, $hash_getVersion_0);
            return (String) r;
        } catch (RuntimeException e) {
            throw e;
        } catch (RemoteException e) {
            throw e;
        } catch (Exception e) {
            throw new UnexpectedException("undeclared checked exception", e);
        }
    }

    /**
     * Asks the server for a connection.
     *
     * @param credentials the credential, or {@code null}
     * @return the connection
     * @throws IOException if it could not be opened
     */
    public RMIConnection newClient(Object credentials) throws IOException {
        try {
            final Object r = ref.invoke(this, $method_newClient_1, new Object[] {credentials},
                    $hash_newClient_1);
            return (RMIConnection) r;
        } catch (RuntimeException e) {
            throw e;
        } catch (RemoteException e) {
            throw e;
        } catch (IOException e) {
            throw e;
        } catch (Exception e) {
            throw new UnexpectedException("undeclared checked exception", e);
        }
    }
}
