package java.rmi.server;

/**
 * A remote method, described by its signature as text.
 *
 * @deprecated the stubs generated by {@code rmic} identified methods by position in an array of
 *     these. Dynamic proxies identify them by a hash of the signature, which does not break on
 *     reordering, and this class was left unused.
 */
@Deprecated(since = "1.2")
public class Operation {

    private final String operation;

    /** With that signature. */
    public Operation(String op) {
        this.operation = op;
    }

    /** The signature. */
    public String getOperation() {
        return this.operation;
    }

    public String toString() {
        return this.operation;
    }
}
