package java.rmi.server;

/**
 * The base of the stubs generated by {@code rmic}.
 *
 * <p>It adds no behaviour over {@link RemoteObject}: what it contributes is the
 * <strong>type</strong>, which was how the runtime recognised a generated stub.
 *
 * @deprecated dynamic proxies generate the stub at run time and do not inherit from this.
 */
@Deprecated(since = "1.5")
public abstract class RemoteStub extends RemoteObject {

    private static final long serialVersionUID = -1585587260594494182L;

    /** Without a reference. */
    protected RemoteStub() {
        super();
    }

    /** With that reference. */
    protected RemoteStub(RemoteRef ref) {
        super(ref);
    }

    /**
     * It sets the reference on a stub.
     *
     * @deprecated it has to be passed through the constructor
     */
    @Deprecated(since = "1.2")
    protected static void setRef(RemoteStub stub, RemoteRef ref) {
        throw new UnsupportedOperationException("the reference goes through the constructor");
    }
}
