package java.rmi.server;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;

/**
 * The handler that turns a call on a proxy into a remote call.
 *
 * <h2>What it replaced</h2>
 *
 * <p>Before this, every remote interface needed a stub generated by {@code rmic} and compiled
 * along with the application — an extra step in the build and a file that drifted out of sync. A
 * dynamic proxy with this handler does the same <strong>at run time</strong>: the call arrives as
 * a {@link Method} and is forwarded through the {@link RemoteRef}.
 *
 * <p>It extends {@link RemoteObject} rather than only implementing {@link InvocationHandler}
 * because it needs the remote identity: {@code equals} and {@code hashCode} on a proxy have to
 * compare the object on the other side, and the base class already does that.
 */
public class RemoteObjectInvocationHandler extends RemoteObject implements InvocationHandler {

    private static final long serialVersionUID = 2L;

    /**
     * @throws NullPointerException if the reference is {@code null}
     */
    public RemoteObjectInvocationHandler(RemoteRef ref) {
        super(ref);
        if (ref == null) {
            throw new NullPointerException("ref");
        }
    }

    /**
     * It forwards the call to the remote object.
     *
     * <p>The three {@link Object} methods are handled locally and do not travel: asking another
     * machine for the {@code hashCode} of its object would be a network round trip for every use in
     * a map, and for {@code equals} it would also be wrong — it is references that must be
     * compared, not objects.
     *
     * @throws IllegalArgumentException if the method is declared by {@link Object} and is not one
     *     of those three. This line used to say it was thrown when the method is not from a remote
     *     interface; the body checks no such thing: any method not declared by {@code Object} goes
     *     straight to {@code getRef().invoke}, and the only {@code throw} is the one for an
     *     unexpected {@code Object} method (checked by reading the body below).
     */
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        if (method.getDeclaringClass() == Object.class) {
            String name = method.getName();
            if (name.equals("hashCode")) {
                return Integer.valueOf(hashCode());
            }
            if (name.equals("equals")) {
                Object other = args[0];
                return Boolean.valueOf(proxy == other
                        || (other != null && java.lang.reflect.Proxy.isProxyClass(other.getClass())
                                && equals(java.lang.reflect.Proxy.getInvocationHandler(other))));
            }
            if (name.equals("toString")) {
                return proxy.getClass().getName() + "[" + getRef().remoteToString() + "]";
            }
            throw new IllegalArgumentException("unexpected method: " + name);
        }
        return getRef().invoke((java.rmi.Remote) proxy, method, args, -1L);
    }
}
