package java.rmi.server;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.io.StreamCorruptedException;

/**
 * A remote call in progress, seen as two streams.
 *
 * @deprecated it dates from the era of stubs generated by {@code rmic}. Dynamic proxies do the same
 *     without exposing the protocol, and none of this has been used since.
 */
@Deprecated(since = "1.2")
public interface RemoteCall {

    /** Where to write the arguments. */
    ObjectOutput getOutputStream() throws IOException;

    /** It finishes writing the arguments. */
    void releaseOutputStream() throws IOException;

    /** Where to read the result from. */
    ObjectInput getInputStream() throws IOException;

    /** It finishes reading. */
    void releaseInputStream() throws IOException;

    /** Where to write the result, on the server side. */
    ObjectOutput getResultStream(boolean success) throws IOException, StreamCorruptedException;

    /** It executes the call. */
    void executeCall() throws Exception;

    /** It releases whatever is still held. */
    void done() throws IOException;
}
