package java.rmi.server;

import java.rmi.Remote;
import java.rmi.server.RemoteStub;

/**
 * The server-side reference of an exported object.
 *
 * @deprecated from the era of the stubs generated by {@code rmic}.
 */
@Deprecated(since = "1.2")
public interface ServerRef extends RemoteRef {

    static final long serialVersionUID = -4557750989390278438L;

    /** It exports the object and returns its stub. */
    RemoteStub exportObject(Remote obj, Object data) throws RemoteException;

    /** The host of the client being served. */
    String getClientHost() throws ServerNotActiveException;
}
