package java.rmi.server;

import java.rmi.RemoteException;
/**
 * The stub and the skeleton are not of the same version.

 * <p>The stubs and skeletons generated by <code>rmic</code> became obsolete with dynamic proxies,
 * and this exception with them.
 *
 * @deprecated nothing has thrown it since skeletons stopped being used.
 */
@Deprecated(since = "1.1")
public class SkeletonMismatchException extends RemoteException {

    private static final long serialVersionUID = -7780460454818859281L;

    /** With a message. */
    public SkeletonMismatchException(String s) {
        super(s);
    }
}
