package java.rmi.server;

import java.rmi.RemoteException;

/**
 * A remote object's skeleton was not found.
 *
 * @deprecated skeletons were used with the stubs generated by {@code rmic}; dynamic proxies
 *     replaced them and nothing throws this.
 */
@Deprecated(since = "1.1")
public class SkeletonNotFoundException extends RemoteException {

    private static final long serialVersionUID = -7860299673822761231L;

    /** With a message. */
    public SkeletonNotFoundException(String s) {
        super(s);
    }

    /** With a message and the cause. */
    public SkeletonNotFoundException(String s, Exception ex) {
        super(s, ex);
    }
}
