package jdk.internal.reflect;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.lang.reflect.UndeclaredThrowableException;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The point EVERY method of EVERY generated proxy class falls into.
 *
 * <h2>Why this class exists and not bytecode</h2>
 *
 * <p>A proxy could be generated with the whole body in bytecode -- it is what the JDK does: each
 * method loads the `h` field, looks its `Method` up in a static field, puts the array together,
 * calls `invoke` and brings a complete `try/catch` in order to translate exceptions. That is a
 * `<clinit>` that resolves methods by name, a table of static fields and a table of exceptions per
 * method: three more generators.
 *
 * <p>Here the generated bytecode does the only thing that cannot be written in Java -- having an
 * arbitrary signature -- and delegates the rest: it pushes `this`, an `int` with the index of the
 * method and the boxed arguments, and calls {@link #dispatch}. Everything else (finding the
 * `Method`, getting the handler, translating whatever is thrown) is written here, in Java, once and
 * not once per generated method.
 *
 * <h2>Why an index and not a name</h2>
 *
 * <p>The index is the position of the method in the table {@link Proxy} registered for that class
 * right after defining it. Numbering instead of naming is what leaves the bytecode with no search
 * at all -- and it is also the only thing that tells apart two methods that share a name and
 * parameters and differ only in the return type, which is legal in a class file and really happens
 * when two interfaces declare covariant returns.
 */
public final class ProxyDispatcher {

    /**
     * From proxy class to its table. Concurrent and not synchronised because it is read on every
     * call to every proxy of the program: a lock there turns every proxy into a point of
     * serialisation. The writing happens once per class, before the first instance exists.
     */
    private static final ConcurrentHashMap<Class<?>, Table> TABLES =
            new ConcurrentHashMap<Class<?>, Table>();

    private ProxyDispatcher() {
    }

    /** What has to be known about a generated method, in two parallel arrays. */
    private static final class Table {
        final Method[] methods;
        final Class<?>[][] declared;

        Table(Method[] methods, Class<?>[][] declared) {
            this.methods = methods;
            this.declared = declared;
        }
    }

    /**
     * It registers the table of a proxy class that has just been defined.
     *
     * <p>{@link Proxy} calls it between `defineClass` and the first instance: in that gap the class
     * exists but nobody can invoke it yet, so there is no race to resolve.
     *
     * @param cls the generated class
     * @param methods the `Method`s in the order in which the bytecode indexes them
     * @param declared for each method, the exceptions it declares after merging those of every
     *        interface that declares it
     */
    public static void register(Class<?> cls, Method[] methods, Class<?>[][] declared) {
        TABLES.put(cls, new Table(methods, declared));
    }

    /**
     * It runs a call to a method of a proxy.
     *
     * <p>The translation of exceptions is the clause of the contract that does not fall out of any
     * choice of bytecode by itself and that is why it is written: the unchecked comes out as it is,
     * the checked that the method declares comes out as it is, and anything else comes out wrapped
     * in {@link UndeclaredThrowableException} -- because a method cannot throw a checked one its
     * signature does not mention, and lying about that breaks the caller.
     *
     * @param proxy the instance it was called on
     * @param index the position of the method in the table of its class
     * @param args the boxed arguments, or `null` if the method takes none
     * @return whatever the handler returns; the bytecode that called casts and unboxes it
     * @throws Throwable whatever the handler throws, already translated
     */
    public static Object dispatch(Object proxy, int index, Object[] args) throws Throwable {
        Table table = TABLES.get(proxy.getClass());
        if (table == null) {
            // It can only happen if somebody defined by hand a class that calls here. It is not a
            // case the contract contemplates, but failing with a message is better than with an
            // NPE.
            throw new InternalError(
                    "proxy with no registered table: " + proxy.getClass().getName());
        }
        Method method = table.methods[index];
        InvocationHandler handler = Proxy.getInvocationHandler(proxy);
        try {
            return handler.invoke(proxy, method, args);
        } catch (RuntimeException unchecked) {
            throw unchecked;
        } catch (Error error) {
            throw error;
        } catch (Throwable checked) {
            Class<?>[] allowed = table.declared[index];
            int i = 0;
            while (i < allowed.length) {
                if (allowed[i].isInstance(checked)) {
                    throw checked;
                }
                i = i + 1;
            }
            throw new UndeclaredThrowableException(checked);
        }
    }
}
