package java.security.interfaces;

import java.math.BigInteger;
import java.security.spec.AlgorithmParameterSpec;

// The DSA domain parameters: the prime p, the subprime q and the generator g.
//
// All three are shared among all the keys of one domain, and without them a DSA key means nothing:
// y = g^x mod p depends on p and g as much as on x.
//
// q is the order of the subgroup generated by g and divides p-1. That a small q exists —160 to 256
// bits against 1024 or 3072 for p— is what makes DSA practical: signatures are the size of q, not
// of p.
public interface DSAParams extends AlgorithmParameterSpec {

    // The large prime.
    BigInteger getP();

    // The subprime: it divides p-1 and fixes the order of the subgroup.
    BigInteger getQ();

    // The generator of the subgroup of order q.
    BigInteger getG();
}
